name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.FSAC_CHECKS_TOKEN }}
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "docs/diagram.svg"
          excluded_paths: "ignore,.paket,paket-files"
