name: Release

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        dotnet: [5.0.200]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Build
      run: dotnet fake build -t Build
    - name: upload artifact package
      uses: actions/upload-artifact@v2
      with:
        name: fsautocomplete
        path: bin/pkgs
    - name: Publish Release
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
        github-token: ${{ secrets.USER_TOKEN }}
      run: dotnet fake build -t Release
